### ISSUE TITLE
error: build of substrate_ros_msgs-master.drv, robonomics_msgs-master.drv failed

### ISSUE THREAD

**Issue by khssnv** [airalab/robonomics#45]
## Summary

An attempt to launch a node by [**3.2. Building with Nix**](https://github.com/airalab/robonomics#32-building-with-nix) guide failed on `catkin_make` stage. Please find logs below.

## System
```console
$ uname -a
Linux myhostname 4.19.101 #1-NixOS SMP Sat Feb 1 09:37:12 UTC 2020 x86_64 GNU/Linux
```

## Logs

<details>
  <summary>$ nix-shell --run "cargo run --release"</summary>

```console
$ nix-shell --run "cargo run --release"
these derivations will be built:
  /nix/store/cfr1hj8krq5fmg0hhsbgahrg38zp2pi4-catkin-0.7.15.drv
  /nix/store/fq1f6xlw6mjlpi4s9z8nwzmlsfdsnfdp-source.drv
  /nix/store/db6y4sdr23ynfzq243sk1xhzmk639ch4-source.drv
  /nix/store/jbsvs7d5ypi17kid8rp7v149lryrwwjx-cmake_modules-0.4.2.drv
  /nix/store/rcmkwpml5f92irabiqiibqx85f3c075j-rospack-2.5.3.drv
  /nix/store/sq48q2agjnzcbmdpg8r1a2q07rs9xjk5-source.drv
  /nix/store/w5i96lcia6j79vrwsi7dmh7xbas8yy14-ros_environment-1.2.1.drv
  /nix/store/0fwzsin6wiy53kqp595fr07hp0r9mmcp-roslib-1.14.6.drv
  /nix/store/r08wc6drwhsg8bx4c9l9050pyv7cfkj1-source.drv
  /nix/store/15r7kim1sjv9a4h1d7jmgdi1ygpbbqzw-rosunit-1.14.6.drv
  /nix/store/rglwhrnfnf5dvx2lbxziff25b8s48pxr-source.drv
  /nix/store/fggl1xn5v45g6p0xm3h2m7y98h9pxiyi-console_bridge-0.3.2.drv
  /nix/store/qbh7irrdvpz0cx87g7vgkrb6s1lhrmfl-source.drv
  /nix/store/n15vc5j7hr03kgbgrsxf74kg7qj06f4g-cpp_common-0.6.11.drv
  /nix/store/s2xqsdsc1z16d9rnfg6f93jjr9hg2lss-source.drv
  /nix/store/fzy7yjjw7wbpdi6966vcasxyn7qirxlm-rostime-0.6.7.drv
  /nix/store/a3p6ykhjdmgap3k2797iwz5vs2zhgzhy-source.drv
  /nix/store/3qrvhg5yz1lwa7k5cpdg10zi53d6x4z7-genmsg-0.5.12.drv
  /nix/store/gcs9j9d25wll71jjghzy7k50591irxpj-source.drv
  /nix/store/6bdd76nqckwj2r1sxr6b5arkl3n4sb3z-genpy-0.6.8.drv
  /nix/store/bq58pizj6cg3civpcvrlmbjfl2n3smpq-source.drv
  /nix/store/86d5dfz41fjvygn9ccfpqmxssq2sv4qb-roscpp_traits-0.6.12.drv
  /nix/store/xvagszvx9pfipxc8yd8dpp9k6nw7c552-source.drv
  /nix/store/v0ysl67ipang3sf31yxpxgm3jzfcbvzs-roscpp_serialization-0.6.12.drv
  /nix/store/5wjmdbndz7sr7qnfz0r0nswc5rz3asz1-source.drv
  /nix/store/y4d7vm27wx26bzjbs4ng27kd9fvgky2k-gencpp-0.6.2.drv
  /nix/store/h10k269c8acch9la6c0j88rv1y3fczg6-message_runtime-0.4.12.drv
  /nix/store/j5kzh9wilkn0bwrfl89lq6n2wy2w0i7x-source.drv
  /nix/store/q0w3jwv1sqywajjf6mscy84bs0yv2kv9-message_generation-0.4.0.drv
  /nix/store/pc9brxr965wvq8c1mzsnr2w3y3d8gpsd-rosbuild-1.14.6.drv
  /nix/store/qsasm6pxrnyh751z35aww9nk9kfghsdr-source.drv
  /nix/store/3s266sy7bxpmlasqhljxdkhgk3v8bn53-rosconsole-1.13.10.drv
  /nix/store/b7j5wh543pbd313glwx62xf53pjx32di-xmlrpcpp-1.14.4.drv
  /nix/store/cyl1c4c5v7150a52bc2si4cdx2i1v57b-source.drv
  /nix/store/dc477wsnv8z2brjh7nd28xsflrm60snn-roslang-1.14.6.drv
  /nix/store/ivx4i6pzjb3492w0921qmplxgqikhbfn-source.drv
  /nix/store/pmcb8j72gicyyfc9iig74bv56v739ix7-std_msgs-0.5.12.drv
  /nix/store/qcs1syl44gjnipzz48sl0q1j792rvlgq-source.drv
  /nix/store/cnpr93wjbgj8rmdrzyclf0hmvaq634di-source.drv
  /nix/store/qmzddbvacw0vzfp5d883q1lg8q81wagm-rosgraph_msgs-1.11.2.drv
  /nix/store/90m6vnxfs756ky7ij394lk9slnyapdb7-roscpp-1.14.4.drv
  /nix/store/gkqpj25mjlyzvb4ad5f92qd11dh2knr8-source.drv
  /nix/store/g9091qiwyrscmbjnqh1hr5n5fb3fvljb-source.drv
  /nix/store/700c1yn5grxxjzlhqnzwyfgw5a2dqz25-source.drv
  /nix/store/k97c8bqwxs0119f2fdskabckl5v8bwjl-rosgraph-1.14.4.drv
  /nix/store/43ssa65g8kknffslwghrbrmyh7hfcyj6-rosmaster-1.14.4.drv
  /nix/store/b4lnai8xs38a4kmnn3ppz5s2x5ch7j7c-source.drv
  /nix/store/nbmjgl24q17sizmlcca4pnghprv5dhgg-source.drv
  /nix/store/c73k9bzxw3p6n5715gvzdkci7d5p61ay-rosclean-1.14.6.drv
  /nix/store/6acglv8jdf71h8rwn1bhz84kclyyplw6-source.drv
  /nix/store/dj9n4fin63cq8ykicclw6xiyfm630yzc-rosout-1.14.4.drv
  /nix/store/vms47dhirrlc5xrbqi402b573ysr7b1q-source.drv
  /nix/store/z7vzsbxkan4mshnad3xzrpn60iw6afwi-rosparam-1.14.4.drv
  /nix/store/6ack0f8fcg4dm6aymxab6y4q551pyaw4-roslaunch-1.14.4.drv
  /nix/store/w3jhrmas29wnfjlj8n0n4v88wzkjs3aw-source.drv
  /nix/store/h3lbl48bscnpckcz34i0w77gh052vrj3-rospy-1.14.4.drv
  /nix/store/ii80kv3jw5hx5bi6h3a4375rzr1a0ldm-rostest-1.14.4.drv
  /nix/store/12zdw7lkyxb0736cfxrxmxm1s59pbqyd-topic_tools-1.14.4.drv
  /nix/store/d0zv8664jyzn0ng0sa5r578w86rnw8ll-roslz4-1.14.4.drv
  /nix/store/lw13axfl7dbgf9b6bdck743pbbxn6568-source.drv
  /nix/store/y8cnajwjag2iv8br3rl4wx4i8pb0ys9p-source.drv
  /nix/store/8v77f11cr0p5jibzdzyliwmpp3h3xjjy-class_loader-0.4.1.drv
  /nix/store/94q8h1n5gln52kscnm282zwc9wxlgpgi-source.drv
  /nix/store/x4iwr1yn4n5pg2jd1ndiky4kn4nn31l5-pluginlib-2.1.1.drv
  /nix/store/4zw8l4rd02zk5cpidh4mnvjmk9vic2x4-rosbag_storage-1.14.4.drv
  /nix/store/7sgxzfqy4fvd6h3mx6iq6065p4bh45sn-source.drv
  /nix/store/d0vpqbx75d6rs359lwrcr4x0jhwfw8wi-std_srvs-1.11.2.drv
  /nix/store/1lk45j5rybv5jq63p1sjz72mycxm520l-rosbag-1.14.4.drv
  /nix/store/iai28ymm691vp13pbwl5ysrx6ap92y7r-source.drv
  /nix/store/13w066spac6rz7nk4i6a0zhjzcnpnjwc-rosmsg-1.14.4.drv
  /nix/store/7jc1pjk8x32bxf34akj2abj3n0acdzj9-source.drv
  /nix/store/8axfcvw061i9ij7m00afv7fy09axghl5-source.drv
  /nix/store/8lzcrkrglyyd2w5q0vwjafcs55zbapjl-source.drv
  /nix/store/jgc10hnc4nn08lb3vvif3yg1m2n0yxzi-source.drv
  /nix/store/p6kkwr0wiv577yfxzhwi2i7ilb9di4l6-rostopic-1.14.4.drv
  /nix/store/8yh5nxgvghl3q1dbvvyvdjgqvdm0m6hs-rosnode-1.14.4.drv
  /nix/store/af0l9hg25c9qy9fzv4y9irb7dnryxs2d-rosboost_cfg-1.14.6.drv
  /nix/store/amp24j2yn7134bh27mcnf3l8rswxxn7z-source.drv
  /nix/store/crqrg1b8wv5a0pg955w9avvfs8gq2a4w-source.drv
  /nix/store/f2hi22pgxa18r9iv478qfxvxzz3pyjdi-source.drv
  /nix/store/h5jpg30q8080lxq9wyqs2wgd5mj5j2wl-rosservice-1.14.4.drv
  /nix/store/ca0niixk8izgxhvx7ai7c1lp3pcwqhpc-roswtf-1.14.4.drv
  /nix/store/hipz94a7vv82w2i06k6ln62ihgcmbvrp-source.drv
  /nix/store/rqb6d9xfdshg8vgm106jybkajrclk6mf-message_filters-1.14.4.drv
  /nix/store/ybjp28dg5rgvhi9xh5v0ds4cffj02s19-source.drv
  /nix/store/hc2ymf6vg4r18v28pq2cmb13v12b0qcx-rosbash-1.14.6.drv
  /nix/store/jvzpclld7mvac59v5lw2x9ljwf5rbkjw-rosmake-1.14.6.drv
  /nix/store/xpwly7q39i7xbnxcdczddvq7sdi9yp81-roscreate-1.14.6.drv
  /nix/store/vwjkp57pxx5pxm27hz9m59kh3i19hw8h-ros-1.14.6.drv
  /nix/store/zp18dbfjcwqrhmc737wfvaydgy4ggynh-ros_comm-1.14.4.drv
  /nix/store/azz2i87rrcshmwilyy14nazjf0skyy1a-substrate_ros_msgs-master.drv
  /nix/store/sq3kkawiqvpbirhh6iijlqi4rrgr2irl-robonomics_msgs-master.drv
building '/nix/store/cfr1hj8krq5fmg0hhsbgahrg38zp2pi4-catkin-0.7.15.drv'...
unpacking sources
unpacking source archive /nix/store/p0s8hkndan2w0p9as70i3hqfr57bs3ab-source
source root is source
patching sources
configuring
fixing cmake files...
cmake flags: -DCMAKE_FIND_USE_SYSTEM_PACKAGE_REGISTRY=OFF -DCMAKE_FIND_USE_PACKAGE_REGISTRY=OFF -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_SKIP_BUILD_RPATH=ON -DBUILD_TESTING=OFF -DCMAKE_INSTALL_LOCALEDIR=/nix/store/j5j8sf9mvffpnlhnzpv05h7i4c4fsb4z-catkin-0.7.15/share/locale -DCMAKE_INSTALL_LIBEXECDIR=/nix/store/j5j8sf9mvffpnlhnzpv05h7i4c4fsb4z-catkin-0.7.15/libexec -DCMAKE_INSTALL_LIBDIR=/nix/store/j5j8sf9mvffpnlhnzpv05h7i4c4fsb4z-catkin-0.7.15/lib -DCMAKE_INSTALL_DOCDIR=/nix/store/j5j8sf9mvffpnlhnzpv05h7i4c4fsb4z-catkin-0.7.15/share/doc/ -DCMAKE_INSTALL_INFODIR=/nix/store/j5j8sf9mvffpnlhnzpv05h7i4c4fsb4z-catkin-0.7.15/share/info -DCMAKE_INSTALL_MANDIR=/nix/store/j5j8sf9mvffpnlhnzpv05h7i4c4fsb4z-catkin-0.7.15/share/man -DCMAKE_INSTALL_OLDINCLUDEDIR=/nix/store/j5j8sf9mvffpnlhnzpv05h7i4c4fsb4z-catkin-0.7.15/include -DCMAKE_INSTALL_INCLUDEDIR=/nix/store/j5j8sf9mvffpnlhnzpv05h7i4c4fsb4z-catkin-0.7.15/include -DCMAKE_INSTALL_SBINDIR=/nix/store/j5j8sf9mvffpnlhnzpv05h7i4c4fsb4z-catkin-0.7.15/sbin -DCMAKE_INSTALL_BINDIR=/nix/store/j5j8sf9mvffpnlhnzpv05h7i4c4fsb4z-catkin-0.7.15/bin -DCMAKE_INSTALL_NAME_DIR=/nix/store/j5j8sf9mvffpnlhnzpv05h7i4c4fsb4z-catkin-0.7.15/lib -DCMAKE_POLICY_DEFAULT_CMP0025=NEW -DCMAKE_OSX_SYSROOT= -DCMAKE_OSX_ARCHITECTURES=x86_64 -DCMAKE_FIND_FRAMEWORK=last -DCMAKE_STRIP=/nix/store/ffi3j388c39qbbskfqg1zw0x2lmbzhnk-binutils-2.31.1/bin/strip -DCMAKE_RANLIB=/nix/store/ffi3j388c39qbbskfqg1zw0x2lmbzhnk-binutils-2.31.1/bin/ranlib -DCMAKE_AR=/nix/store/ffi3j388c39qbbskfqg1zw0x2lmbzhnk-binutils-2.31.1/bin/ar -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DCMAKE_INSTALL_PREFIX=/nix/store/j5j8sf9mvffpnlhnzpv05h7i4c4fsb4z-catkin-0.7.15 -DCATKIN_ENABLE_TESTING=OFF -DSETUPTOOLS_DEB_LAYOUT=OFF
-- The C compiler identification is GNU 9.2.0
-- The CXX compiler identification is GNU 9.2.0
-- Check for working C compiler: /nix/store/1kn7fi3hhi33jms3113riyzwyn2yqpqd-gcc-wrapper-9.2.0/bin/gcc
-- Check for working C compiler: /nix/store/1kn7fi3hhi33jms3113riyzwyn2yqpqd-gcc-wrapper-9.2.0/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /nix/store/1kn7fi3hhi33jms3113riyzwyn2yqpqd-gcc-wrapper-9.2.0/bin/g++
-- Check for working CXX compiler: /nix/store/1kn7fi3hhi33jms3113riyzwyn2yqpqd-gcc-wrapper-9.2.0/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using CATKIN_DEVEL_PREFIX: /build/source/build/devel
-- Using CMAKE_PREFIX_PATH: /nix/store/9l2zg4lazdld9v3mhcmcmdh0cx0qf753-patchelf-0.9;/nix/store/1kn7fi3hhi33jms3113riyzwyn2yqpqd-gcc-wrapper-9.2.0;/nix/store/662pxfcxbldq4k00ck53bn33g04ysywk-binutils-wrapper-2.31.1;/nix/store/kzrvnyppsbb86vga4ww832fdck7yfk8n-python3.7-catkin_pkg-0.4.9;/nix/store/zbjznzbm1ldmhdnzxws1cm97pdcvqina-python3.7-pyparsing-2.4.6;/nix/store/ja04f3cmapzb3f2mvjrb883bfqclsirq-python3-3.7.6;/nix/store/jsx5s3fdd2zxs357sgbwsx932f1kwi4g-python3.7-docutils-0.16;/nix/store/ddivg8kiahl1kllshyz4shhyky8ppz2v-python3.7-python-dateutil-2.8.1;/nix/store/l9yvb1hg4prpzv91bkfw1mdpqax3l5m9-python3.7-six-1.14.0;/nix/store/16irg1bsnkyzp4rbmfa5df1b3kw55v4s-python3.7-setuptools_scm-3.4.3;/nix/store/8ydppw7ymyh32iqdjagcpzi9hh7vyd9w-python3.7-rospkg-1.1.7;/nix/store/fnyf2aki0gbf0zqk98b6nks89awcd5j5-python3.7-PyYAML-5.2;/nix/store/hh5z7zyfgsv38azgk43ync9yc6z4cv1r-empy-3.3.2;/nix/store/41irrnq4ki4yijrh1z2by148xhhws0cq-cmake-3.16.4
-- Found PythonInterp: /nix/store/ja04f3cmapzb3f2mvjrb883bfqclsirq-python3-3.7.6/bin/python (found version "3.7.6")
-- Using PYTHON_EXECUTABLE: /nix/store/ja04f3cmapzb3f2mvjrb883bfqclsirq-python3-3.7.6/bin/python
-- Using default Python package layout
-- Found PY_em: /nix/store/hh5z7zyfgsv38azgk43ync9yc6z4cv1r-empy-3.3.2/lib/python3.7/site-packages/em.py
-- Using empy: /nix/store/hh5z7zyfgsv38azgk43ync9yc6z4cv1r-empy-3.3.2/lib/python3.7/site-packages/em.py
-- Using CATKIN_ENABLE_TESTING: OFF
-- catkin 0.7.15
-- BUILD_SHARED_LIBS is on
Traceback (most recent call last):
  File "/build/source/build/catkin_generated/generate_cached_setup.py", line 22, in <module>
    code = generate_environment_script('/build/source/build/devel/env.sh')
  File "/build/source/cmake/../python/catkin/environment_cache.py", line 61, in generate_environment_script
    output = subprocess.check_output([env_script, sys.executable, '-c', python_code])
  File "/nix/store/ja04f3cmapzb3f2mvjrb883bfqclsirq-python3-3.7.6/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/nix/store/ja04f3cmapzb3f2mvjrb883bfqclsirq-python3-3.7.6/lib/python3.7/subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/nix/store/ja04f3cmapzb3f2mvjrb883bfqclsirq-python3-3.7.6/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/nix/store/ja04f3cmapzb3f2mvjrb883bfqclsirq-python3-3.7.6/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/build/source/build/devel/env.sh': '/build/source/build/devel/env.sh'
CMake Error at cmake/safe_execute_process.cmake:11 (message):

  execute_process(/nix/store/ja04f3cmapzb3f2mvjrb883bfqclsirq-python3-3.7.6/bin/python
  "/build/source/build/catkin_generated/generate_cached_setup.py") returned
  error code 1
Call Stack (most recent call first):
  cmake/all.cmake:207 (safe_execute_process)
  CMakeLists.txt:8 (include)


-- Configuring incomplete, errors occurred!
See also "/build/source/build/CMakeFiles/CMakeOutput.log".
builder for '/nix/store/cfr1hj8krq5fmg0hhsbgahrg38zp2pi4-catkin-0.7.15.drv' failed with exit code 1
cannot build derivation '/nix/store/sq3kkawiqvpbirhh6iijlqi4rrgr2irl-robonomics_msgs-master.drv': 1 dependencies couldn't be built
error: build of '/nix/store/azz2i87rrcshmwilyy14nazjf0skyy1a-substrate_ros_msgs-master.drv', '/nix/store/sq3kkawiqvpbirhh6iijlqi4rrgr2irl-robonomics_msgs-master.drv' failed
```

</details>

**Comment by akru** [comment]
Fixed, in `airapkgs`, workflow will be checked at https://github.com/airalab/robonomics/runs/498827735

**Comment by akru** [comment]
Related to https://github.com/airalab/robonomics/issues/43

**Comment by khssnv** [comment]
Seems like still an issue the same. Please find a build log below.

<details>
  <summary>$ nix-shell --run "cargo run --release"</summary>

```console
$ nix-shell --run "cargo run --release"
these derivations will be built:
  /nix/store/cfr1hj8krq5fmg0hhsbgahrg38zp2pi4-catkin-0.7.15.drv
  /nix/store/fq1f6xlw6mjlpi4s9z8nwzmlsfdsnfdp-source.drv
  /nix/store/db6y4sdr23ynfzq243sk1xhzmk639ch4-source.drv
  /nix/store/jbsvs7d5ypi17kid8rp7v149lryrwwjx-cmake_modules-0.4.2.drv
  /nix/store/rcmkwpml5f92irabiqiibqx85f3c075j-rospack-2.5.3.drv
  /nix/store/sq48q2agjnzcbmdpg8r1a2q07rs9xjk5-source.drv
  /nix/store/w5i96lcia6j79vrwsi7dmh7xbas8yy14-ros_environment-1.2.1.drv
  /nix/store/0fwzsin6wiy53kqp595fr07hp0r9mmcp-roslib-1.14.6.drv
  /nix/store/r08wc6drwhsg8bx4c9l9050pyv7cfkj1-source.drv
  /nix/store/15r7kim1sjv9a4h1d7jmgdi1ygpbbqzw-rosunit-1.14.6.drv
  /nix/store/rglwhrnfnf5dvx2lbxziff25b8s48pxr-source.drv
  /nix/store/fggl1xn5v45g6p0xm3h2m7y98h9pxiyi-console_bridge-0.3.2.drv
  /nix/store/qbh7irrdvpz0cx87g7vgkrb6s1lhrmfl-source.drv
  /nix/store/n15vc5j7hr03kgbgrsxf74kg7qj06f4g-cpp_common-0.6.11.drv
  /nix/store/s2xqsdsc1z16d9rnfg6f93jjr9hg2lss-source.drv
  /nix/store/fzy7yjjw7wbpdi6966vcasxyn7qirxlm-rostime-0.6.7.drv
  /nix/store/a3p6ykhjdmgap3k2797iwz5vs2zhgzhy-source.drv
  /nix/store/3qrvhg5yz1lwa7k5cpdg10zi53d6x4z7-genmsg-0.5.12.drv
  /nix/store/gcs9j9d25wll71jjghzy7k50591irxpj-source.drv
  /nix/store/6bdd76nqckwj2r1sxr6b5arkl3n4sb3z-genpy-0.6.8.drv
  /nix/store/bq58pizj6cg3civpcvrlmbjfl2n3smpq-source.drv
  /nix/store/86d5dfz41fjvygn9ccfpqmxssq2sv4qb-roscpp_traits-0.6.12.drv
  /nix/store/xvagszvx9pfipxc8yd8dpp9k6nw7c552-source.drv
  /nix/store/v0ysl67ipang3sf31yxpxgm3jzfcbvzs-roscpp_serialization-0.6.12.drv
  /nix/store/5wjmdbndz7sr7qnfz0r0nswc5rz3asz1-source.drv
  /nix/store/y4d7vm27wx26bzjbs4ng27kd9fvgky2k-gencpp-0.6.2.drv
  /nix/store/h10k269c8acch9la6c0j88rv1y3fczg6-message_runtime-0.4.12.drv
  /nix/store/j5kzh9wilkn0bwrfl89lq6n2wy2w0i7x-source.drv
  /nix/store/q0w3jwv1sqywajjf6mscy84bs0yv2kv9-message_generation-0.4.0.drv
  /nix/store/pc9brxr965wvq8c1mzsnr2w3y3d8gpsd-rosbuild-1.14.6.drv
  /nix/store/qsasm6pxrnyh751z35aww9nk9kfghsdr-source.drv
  /nix/store/3s266sy7bxpmlasqhljxdkhgk3v8bn53-rosconsole-1.13.10.drv
  /nix/store/b7j5wh543pbd313glwx62xf53pjx32di-xmlrpcpp-1.14.4.drv
  /nix/store/cyl1c4c5v7150a52bc2si4cdx2i1v57b-source.drv
  /nix/store/dc477wsnv8z2brjh7nd28xsflrm60snn-roslang-1.14.6.drv
  /nix/store/ivx4i6pzjb3492w0921qmplxgqikhbfn-source.drv
  /nix/store/pmcb8j72gicyyfc9iig74bv56v739ix7-std_msgs-0.5.12.drv
  /nix/store/qcs1syl44gjnipzz48sl0q1j792rvlgq-source.drv
  /nix/store/cnpr93wjbgj8rmdrzyclf0hmvaq634di-source.drv
  /nix/store/qmzddbvacw0vzfp5d883q1lg8q81wagm-rosgraph_msgs-1.11.2.drv
  /nix/store/90m6vnxfs756ky7ij394lk9slnyapdb7-roscpp-1.14.4.drv
  /nix/store/gkqpj25mjlyzvb4ad5f92qd11dh2knr8-source.drv
  /nix/store/g9091qiwyrscmbjnqh1hr5n5fb3fvljb-source.drv
  /nix/store/700c1yn5grxxjzlhqnzwyfgw5a2dqz25-source.drv
  /nix/store/k97c8bqwxs0119f2fdskabckl5v8bwjl-rosgraph-1.14.4.drv
  /nix/store/43ssa65g8kknffslwghrbrmyh7hfcyj6-rosmaster-1.14.4.drv
  /nix/store/b4lnai8xs38a4kmnn3ppz5s2x5ch7j7c-source.drv
  /nix/store/nbmjgl24q17sizmlcca4pnghprv5dhgg-source.drv
  /nix/store/c73k9bzxw3p6n5715gvzdkci7d5p61ay-rosclean-1.14.6.drv
  /nix/store/6acglv8jdf71h8rwn1bhz84kclyyplw6-source.drv
  /nix/store/dj9n4fin63cq8ykicclw6xiyfm630yzc-rosout-1.14.4.drv
  /nix/store/vms47dhirrlc5xrbqi402b573ysr7b1q-source.drv
  /nix/store/z7vzsbxkan4mshnad3xzrpn60iw6afwi-rosparam-1.14.4.drv
  /nix/store/6ack0f8fcg4dm6aymxab6y4q551pyaw4-roslaunch-1.14.4.drv
  /nix/store/w3jhrmas29wnfjlj8n0n4v88wzkjs3aw-source.drv
  /nix/store/h3lbl48bscnpckcz34i0w77gh052vrj3-rospy-1.14.4.drv
  /nix/store/ii80kv3jw5hx5bi6h3a4375rzr1a0ldm-rostest-1.14.4.drv
  /nix/store/12zdw7lkyxb0736cfxrxmxm1s59pbqyd-topic_tools-1.14.4.drv
  /nix/store/f2hi22pgxa18r9iv478qfxvxzz3pyjdi-source.drv
  /nix/store/iai28ymm691vp13pbwl5ysrx6ap92y7r-source.drv
  /nix/store/d0zv8664jyzn0ng0sa5r578w86rnw8ll-roslz4-1.14.4.drv
  /nix/store/lw13axfl7dbgf9b6bdck743pbbxn6568-source.drv
  /nix/store/y8cnajwjag2iv8br3rl4wx4i8pb0ys9p-source.drv
  /nix/store/8v77f11cr0p5jibzdzyliwmpp3h3xjjy-class_loader-0.4.1.drv
  /nix/store/94q8h1n5gln52kscnm282zwc9wxlgpgi-source.drv
  /nix/store/x4iwr1yn4n5pg2jd1ndiky4kn4nn31l5-pluginlib-2.1.1.drv
  /nix/store/4zw8l4rd02zk5cpidh4mnvjmk9vic2x4-rosbag_storage-1.14.4.drv
  /nix/store/7sgxzfqy4fvd6h3mx6iq6065p4bh45sn-source.drv
  /nix/store/d0vpqbx75d6rs359lwrcr4x0jhwfw8wi-std_srvs-1.11.2.drv
  /nix/store/lkw5hqfhvwwp87pkq2vzcn3ndpld9ds2-rosbag-1.14.4.drv
  /nix/store/vrhkd0kfr5r0c1vaqiw8bdyb85bwgdhm-rosmsg-1.14.4.drv
  /nix/store/3zwfmwgyhdbfykf732k1x01ibizywss8-rosservice-1.14.4.drv
  /nix/store/7jc1pjk8x32bxf34akj2abj3n0acdzj9-source.drv
  /nix/store/8axfcvw061i9ij7m00afv7fy09axghl5-source.drv
  /nix/store/jgc10hnc4nn08lb3vvif3yg1m2n0yxzi-source.drv
  /nix/store/sign97c3acg3k67n0vbyydin7j8h4k3w-rostopic-1.14.4.drv
  /nix/store/a967h41plmiznmy7pggb84ic1d41vw23-rosnode-1.14.4.drv
  /nix/store/crqrg1b8wv5a0pg955w9avvfs8gq2a4w-source.drv
  /nix/store/bs3jigc51wap0c4ckl2484phkzwcrwqk-roswtf-1.14.4.drv
  /nix/store/hipz94a7vv82w2i06k6ln62ihgcmbvrp-source.drv
  /nix/store/amp24j2yn7134bh27mcnf3l8rswxxn7z-source.drv
  /nix/store/rqb6d9xfdshg8vgm106jybkajrclk6mf-message_filters-1.14.4.drv
  /nix/store/af0l9hg25c9qy9fzv4y9irb7dnryxs2d-rosboost_cfg-1.14.6.drv
  /nix/store/ybjp28dg5rgvhi9xh5v0ds4cffj02s19-source.drv
  /nix/store/hc2ymf6vg4r18v28pq2cmb13v12b0qcx-rosbash-1.14.6.drv
  /nix/store/jvzpclld7mvac59v5lw2x9ljwf5rbkjw-rosmake-1.14.6.drv
  /nix/store/8lzcrkrglyyd2w5q0vwjafcs55zbapjl-source.drv
  /nix/store/xpwly7q39i7xbnxcdczddvq7sdi9yp81-roscreate-1.14.6.drv
  /nix/store/vwjkp57pxx5pxm27hz9m59kh3i19hw8h-ros-1.14.6.drv
  /nix/store/lyqhq437m9zr7vwm36wcn5c5cd6k11nl-ros_comm-1.14.4.drv
  /nix/store/jg8bmqd98411gcjw6k336r97y8zx8z6q-substrate_ros_msgs-master.drv
  /nix/store/8hn4ncxn5ql2bpvnbr4hsd3kq66aaflz-robonomics_msgs-master.drv
these paths will be fetched (6.82 MiB download, 24.01 MiB unpacked):
  /nix/store/1nii7hnrw3cg8ci9r6pjxn1jd0c77jaf-python3.7-pycryptodomex-3.9.4
building '/nix/store/cfr1hj8krq5fmg0hhsbgahrg38zp2pi4-catkin-0.7.15.drv'...
unpacking sources
unpacking source archive /nix/store/p0s8hkndan2w0p9as70i3hqfr57bs3ab-source
source root is source
patching sources
configuring
fixing cmake files...
cmake flags: -DCMAKE_FIND_USE_SYSTEM_PACKAGE_REGISTRY=OFF -DCMAKE_FIND_USE_PACKAGE_REGISTRY=OFF -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_SKIP_BUILD_RPATH=ON -DBUILD_TESTING=OFF -DCMAKE_INSTALL_LOCALEDIR=/nix/store/j5j8sf9mvffpnlhnzpv05h7i4c4fsb4z-catkin-0.7.15/share/locale -DCMAKE_INSTALL_LIBEXECDIR=/nix/store/j5j8sf9mvffpnlhnzpv05h7i4c4fsb4z-catkin-0.7.15/libexec -DCMAKE_INSTALL_LIBDIR=/nix/store/j5j8sf9mvffpnlhnzpv05h7i4c4fsb4z-catkin-0.7.15/lib -DCMAKE_INSTALL_DOCDIR=/nix/store/j5j8sf9mvffpnlhnzpv05h7i4c4fsb4z-catkin-0.7.15/share/doc/ -DCMAKE_INSTALL_INFODIR=/nix/store/j5j8sf9mvffpnlhnzpv05h7i4c4fsb4z-catkin-0.7.15/share/info -DCMAKE_INSTALL_MANDIR=/nix/store/j5j8sf9mvffpnlhnzpv05h7i4c4fsb4z-catkin-0.7.15/share/man -DCMAKE_INSTALL_OLDINCLUDEDIR=/nix/store/j5j8sf9mvffpnlhnzpv05h7i4c4fsb4z-catkin-0.7.15/include -DCMAKE_INSTALL_INCLUDEDIR=/nix/store/j5j8sf9mvffpnlhnzpv05h7i4c4fsb4z-catkin-0.7.15/include -DCMAKE_INSTALL_SBINDIR=/nix/store/j5j8sf9mvffpnlhnzpv05h7i4c4fsb4z-catkin-0.7.15/sbin -DCMAKE_INSTALL_BINDIR=/nix/store/j5j8sf9mvffpnlhnzpv05h7i4c4fsb4z-catkin-0.7.15/bin -DCMAKE_INSTALL_NAME_DIR=/nix/store/j5j8sf9mvffpnlhnzpv05h7i4c4fsb4z-catkin-0.7.15/lib -DCMAKE_POLICY_DEFAULT_CMP0025=NEW -DCMAKE_OSX_SYSROOT= -DCMAKE_OSX_ARCHITECTURES=x86_64 -DCMAKE_FIND_FRAMEWORK=last -DCMAKE_STRIP=/nix/store/ffi3j388c39qbbskfqg1zw0x2lmbzhnk-binutils-2.31.1/bin/strip -DCMAKE_RANLIB=/nix/store/ffi3j388c39qbbskfqg1zw0x2lmbzhnk-binutils-2.31.1/bin/ranlib -DCMAKE_AR=/nix/store/ffi3j388c39qbbskfqg1zw0x2lmbzhnk-binutils-2.31.1/bin/ar -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DCMAKE_INSTALL_PREFIX=/nix/store/j5j8sf9mvffpnlhnzpv05h7i4c4fsb4z-catkin-0.7.15 -DCATKIN_ENABLE_TESTING=OFF -DSETUPTOOLS_DEB_LAYOUT=OFF
-- The C compiler identification is GNU 9.2.0
-- The CXX compiler identification is GNU 9.2.0
-- Check for working C compiler: /nix/store/1kn7fi3hhi33jms3113riyzwyn2yqpqd-gcc-wrapper-9.2.0/bin/gcc
-- Check for working C compiler: /nix/store/1kn7fi3hhi33jms3113riyzwyn2yqpqd-gcc-wrapper-9.2.0/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /nix/store/1kn7fi3hhi33jms3113riyzwyn2yqpqd-gcc-wrapper-9.2.0/bin/g++
-- Check for working CXX compiler: /nix/store/1kn7fi3hhi33jms3113riyzwyn2yqpqd-gcc-wrapper-9.2.0/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using CATKIN_DEVEL_PREFIX: /build/source/build/devel
-- Using CMAKE_PREFIX_PATH: /nix/store/9l2zg4lazdld9v3mhcmcmdh0cx0qf753-patchelf-0.9;/nix/store/1kn7fi3hhi33jms3113riyzwyn2yqpqd-gcc-wrapper-9.2.0;/nix/store/662pxfcxbldq4k00ck53bn33g04ysywk-binutils-wrapper-2.31.1;/nix/store/kzrvnyppsbb86vga4ww832fdck7yfk8n-python3.7-catkin_pkg-0.4.9;/nix/store/zbjznzbm1ldmhdnzxws1cm97pdcvqina-python3.7-pyparsing-2.4.6;/nix/store/ja04f3cmapzb3f2mvjrb883bfqclsirq-python3-3.7.6;/nix/store/jsx5s3fdd2zxs357sgbwsx932f1kwi4g-python3.7-docutils-0.16;/nix/store/ddivg8kiahl1kllshyz4shhyky8ppz2v-python3.7-python-dateutil-2.8.1;/nix/store/l9yvb1hg4prpzv91bkfw1mdpqax3l5m9-python3.7-six-1.14.0;/nix/store/16irg1bsnkyzp4rbmfa5df1b3kw55v4s-python3.7-setuptools_scm-3.4.3;/nix/store/8ydppw7ymyh32iqdjagcpzi9hh7vyd9w-python3.7-rospkg-1.1.7;/nix/store/fnyf2aki0gbf0zqk98b6nks89awcd5j5-python3.7-PyYAML-5.2;/nix/store/hh5z7zyfgsv38azgk43ync9yc6z4cv1r-empy-3.3.2;/nix/store/41irrnq4ki4yijrh1z2by148xhhws0cq-cmake-3.16.4
-- Found PythonInterp: /nix/store/ja04f3cmapzb3f2mvjrb883bfqclsirq-python3-3.7.6/bin/python (found version "3.7.6")
-- Using PYTHON_EXECUTABLE: /nix/store/ja04f3cmapzb3f2mvjrb883bfqclsirq-python3-3.7.6/bin/python
-- Using default Python package layout
-- Found PY_em: /nix/store/hh5z7zyfgsv38azgk43ync9yc6z4cv1r-empy-3.3.2/lib/python3.7/site-packages/em.py
-- Using empy: /nix/store/hh5z7zyfgsv38azgk43ync9yc6z4cv1r-empy-3.3.2/lib/python3.7/site-packages/em.py
-- Using CATKIN_ENABLE_TESTING: OFF
-- catkin 0.7.15
-- BUILD_SHARED_LIBS is on
Traceback (most recent call last):
  File "/build/source/build/catkin_generated/generate_cached_setup.py", line 22, in <module>
    code = generate_environment_script('/build/source/build/devel/env.sh')
  File "/build/source/cmake/../python/catkin/environment_cache.py", line 61, in generate_environment_script
    output = subprocess.check_output([env_script, sys.executable, '-c', python_code])
  File "/nix/store/ja04f3cmapzb3f2mvjrb883bfqclsirq-python3-3.7.6/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/nix/store/ja04f3cmapzb3f2mvjrb883bfqclsirq-python3-3.7.6/lib/python3.7/subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/nix/store/ja04f3cmapzb3f2mvjrb883bfqclsirq-python3-3.7.6/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/nix/store/ja04f3cmapzb3f2mvjrb883bfqclsirq-python3-3.7.6/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/build/source/build/devel/env.sh': '/build/source/build/devel/env.sh'
CMake Error at cmake/safe_execute_process.cmake:11 (message):

  execute_process(/nix/store/ja04f3cmapzb3f2mvjrb883bfqclsirq-python3-3.7.6/bin/python
  "/build/source/build/catkin_generated/generate_cached_setup.py") returned
  error code 1
Call Stack (most recent call first):
  cmake/all.cmake:207 (safe_execute_process)
  CMakeLists.txt:8 (include)


-- Configuring incomplete, errors occurred!
See also "/build/source/build/CMakeFiles/CMakeOutput.log".
builder for '/nix/store/cfr1hj8krq5fmg0hhsbgahrg38zp2pi4-catkin-0.7.15.drv' failed with exit code 1
cannot build derivation '/nix/store/8hn4ncxn5ql2bpvnbr4hsd3kq66aaflz-robonomics_msgs-master.drv': 1 dependencies couldn't be built
error: build of '/nix/store/8hn4ncxn5ql2bpvnbr4hsd3kq66aaflz-robonomics_msgs-master.drv', '/nix/store/jg8bmqd98411gcjw6k336r97y8zx8z6q-substrate_ros_msgs-master.drv' failed
```

</details>

**Comment by akru** [comment]
Sure, it's sandbox:
please try: `$ nix-shell --option sandbox false --run "cargo run --release"`

**Comment by khssnv** [comment]
> Sure, it's sandbox:
> please try: `$ nix-shell --option sandbox false --run "cargo run --release"`

The same with sandbox disabled. Please find a log below.

<details>
  <summary>$ nix-shell --option sandbox false --run "cargo run --release"</summary>

```console
$ nix-shell --option sandbox false --run "cargo run --release"
warning: ignoring the user-specified setting 'sandbox', because it is a restricted setting and you are not a trusted user
these derivations will be built:
  /nix/store/cfr1hj8krq5fmg0hhsbgahrg38zp2pi4-catkin-0.7.15.drv
  /nix/store/fq1f6xlw6mjlpi4s9z8nwzmlsfdsnfdp-source.drv
  /nix/store/db6y4sdr23ynfzq243sk1xhzmk639ch4-source.drv
  /nix/store/jbsvs7d5ypi17kid8rp7v149lryrwwjx-cmake_modules-0.4.2.drv
  /nix/store/rcmkwpml5f92irabiqiibqx85f3c075j-rospack-2.5.3.drv
  /nix/store/sq48q2agjnzcbmdpg8r1a2q07rs9xjk5-source.drv
  /nix/store/w5i96lcia6j79vrwsi7dmh7xbas8yy14-ros_environment-1.2.1.drv
  /nix/store/0fwzsin6wiy53kqp595fr07hp0r9mmcp-roslib-1.14.6.drv
  /nix/store/r08wc6drwhsg8bx4c9l9050pyv7cfkj1-source.drv
  /nix/store/15r7kim1sjv9a4h1d7jmgdi1ygpbbqzw-rosunit-1.14.6.drv
  /nix/store/rglwhrnfnf5dvx2lbxziff25b8s48pxr-source.drv
  /nix/store/fggl1xn5v45g6p0xm3h2m7y98h9pxiyi-console_bridge-0.3.2.drv
  /nix/store/qbh7irrdvpz0cx87g7vgkrb6s1lhrmfl-source.drv
  /nix/store/n15vc5j7hr03kgbgrsxf74kg7qj06f4g-cpp_common-0.6.11.drv
  /nix/store/s2xqsdsc1z16d9rnfg6f93jjr9hg2lss-source.drv
  /nix/store/fzy7yjjw7wbpdi6966vcasxyn7qirxlm-rostime-0.6.7.drv
  /nix/store/a3p6ykhjdmgap3k2797iwz5vs2zhgzhy-source.drv
  /nix/store/3qrvhg5yz1lwa7k5cpdg10zi53d6x4z7-genmsg-0.5.12.drv
  /nix/store/gcs9j9d25wll71jjghzy7k50591irxpj-source.drv
  /nix/store/6bdd76nqckwj2r1sxr6b5arkl3n4sb3z-genpy-0.6.8.drv
  /nix/store/bq58pizj6cg3civpcvrlmbjfl2n3smpq-source.drv
  /nix/store/86d5dfz41fjvygn9ccfpqmxssq2sv4qb-roscpp_traits-0.6.12.drv
  /nix/store/xvagszvx9pfipxc8yd8dpp9k6nw7c552-source.drv
  /nix/store/v0ysl67ipang3sf31yxpxgm3jzfcbvzs-roscpp_serialization-0.6.12.drv
  /nix/store/5wjmdbndz7sr7qnfz0r0nswc5rz3asz1-source.drv
  /nix/store/y4d7vm27wx26bzjbs4ng27kd9fvgky2k-gencpp-0.6.2.drv
  /nix/store/h10k269c8acch9la6c0j88rv1y3fczg6-message_runtime-0.4.12.drv
  /nix/store/j5kzh9wilkn0bwrfl89lq6n2wy2w0i7x-source.drv
  /nix/store/q0w3jwv1sqywajjf6mscy84bs0yv2kv9-message_generation-0.4.0.drv
  /nix/store/pc9brxr965wvq8c1mzsnr2w3y3d8gpsd-rosbuild-1.14.6.drv
  /nix/store/qsasm6pxrnyh751z35aww9nk9kfghsdr-source.drv
  /nix/store/3s266sy7bxpmlasqhljxdkhgk3v8bn53-rosconsole-1.13.10.drv
  /nix/store/b7j5wh543pbd313glwx62xf53pjx32di-xmlrpcpp-1.14.4.drv
  /nix/store/cyl1c4c5v7150a52bc2si4cdx2i1v57b-source.drv
  /nix/store/dc477wsnv8z2brjh7nd28xsflrm60snn-roslang-1.14.6.drv
  /nix/store/ivx4i6pzjb3492w0921qmplxgqikhbfn-source.drv
  /nix/store/pmcb8j72gicyyfc9iig74bv56v739ix7-std_msgs-0.5.12.drv
  /nix/store/qcs1syl44gjnipzz48sl0q1j792rvlgq-source.drv
  /nix/store/cnpr93wjbgj8rmdrzyclf0hmvaq634di-source.drv
  /nix/store/qmzddbvacw0vzfp5d883q1lg8q81wagm-rosgraph_msgs-1.11.2.drv
  /nix/store/90m6vnxfs756ky7ij394lk9slnyapdb7-roscpp-1.14.4.drv
  /nix/store/gkqpj25mjlyzvb4ad5f92qd11dh2knr8-source.drv
  /nix/store/g9091qiwyrscmbjnqh1hr5n5fb3fvljb-source.drv
  /nix/store/700c1yn5grxxjzlhqnzwyfgw5a2dqz25-source.drv
  /nix/store/k97c8bqwxs0119f2fdskabckl5v8bwjl-rosgraph-1.14.4.drv
  /nix/store/43ssa65g8kknffslwghrbrmyh7hfcyj6-rosmaster-1.14.4.drv
  /nix/store/b4lnai8xs38a4kmnn3ppz5s2x5ch7j7c-source.drv
  /nix/store/nbmjgl24q17sizmlcca4pnghprv5dhgg-source.drv
  /nix/store/c73k9bzxw3p6n5715gvzdkci7d5p61ay-rosclean-1.14.6.drv
  /nix/store/6acglv8jdf71h8rwn1bhz84kclyyplw6-source.drv
  /nix/store/dj9n4fin63cq8ykicclw6xiyfm630yzc-rosout-1.14.4.drv
  /nix/store/vms47dhirrlc5xrbqi402b573ysr7b1q-source.drv
  /nix/store/z7vzsbxkan4mshnad3xzrpn60iw6afwi-rosparam-1.14.4.drv
  /nix/store/6ack0f8fcg4dm6aymxab6y4q551pyaw4-roslaunch-1.14.4.drv
  /nix/store/w3jhrmas29wnfjlj8n0n4v88wzkjs3aw-source.drv
  /nix/store/h3lbl48bscnpckcz34i0w77gh052vrj3-rospy-1.14.4.drv
  /nix/store/ii80kv3jw5hx5bi6h3a4375rzr1a0ldm-rostest-1.14.4.drv
  /nix/store/12zdw7lkyxb0736cfxrxmxm1s59pbqyd-topic_tools-1.14.4.drv
  /nix/store/f2hi22pgxa18r9iv478qfxvxzz3pyjdi-source.drv
  /nix/store/iai28ymm691vp13pbwl5ysrx6ap92y7r-source.drv
  /nix/store/d0zv8664jyzn0ng0sa5r578w86rnw8ll-roslz4-1.14.4.drv
  /nix/store/lw13axfl7dbgf9b6bdck743pbbxn6568-source.drv
  /nix/store/y8cnajwjag2iv8br3rl4wx4i8pb0ys9p-source.drv
  /nix/store/8v77f11cr0p5jibzdzyliwmpp3h3xjjy-class_loader-0.4.1.drv
  /nix/store/94q8h1n5gln52kscnm282zwc9wxlgpgi-source.drv
  /nix/store/x4iwr1yn4n5pg2jd1ndiky4kn4nn31l5-pluginlib-2.1.1.drv
  /nix/store/4zw8l4rd02zk5cpidh4mnvjmk9vic2x4-rosbag_storage-1.14.4.drv
  /nix/store/7sgxzfqy4fvd6h3mx6iq6065p4bh45sn-source.drv
  /nix/store/d0vpqbx75d6rs359lwrcr4x0jhwfw8wi-std_srvs-1.11.2.drv
  /nix/store/lkw5hqfhvwwp87pkq2vzcn3ndpld9ds2-rosbag-1.14.4.drv
  /nix/store/vrhkd0kfr5r0c1vaqiw8bdyb85bwgdhm-rosmsg-1.14.4.drv
  /nix/store/3zwfmwgyhdbfykf732k1x01ibizywss8-rosservice-1.14.4.drv
  /nix/store/7jc1pjk8x32bxf34akj2abj3n0acdzj9-source.drv
  /nix/store/8axfcvw061i9ij7m00afv7fy09axghl5-source.drv
  /nix/store/jgc10hnc4nn08lb3vvif3yg1m2n0yxzi-source.drv
  /nix/store/sign97c3acg3k67n0vbyydin7j8h4k3w-rostopic-1.14.4.drv
  /nix/store/a967h41plmiznmy7pggb84ic1d41vw23-rosnode-1.14.4.drv
  /nix/store/crqrg1b8wv5a0pg955w9avvfs8gq2a4w-source.drv
  /nix/store/bs3jigc51wap0c4ckl2484phkzwcrwqk-roswtf-1.14.4.drv
  /nix/store/hipz94a7vv82w2i06k6ln62ihgcmbvrp-source.drv
  /nix/store/amp24j2yn7134bh27mcnf3l8rswxxn7z-source.drv
  /nix/store/rqb6d9xfdshg8vgm106jybkajrclk6mf-message_filters-1.14.4.drv
  /nix/store/af0l9hg25c9qy9fzv4y9irb7dnryxs2d-rosboost_cfg-1.14.6.drv
  /nix/store/ybjp28dg5rgvhi9xh5v0ds4cffj02s19-source.drv
  /nix/store/hc2ymf6vg4r18v28pq2cmb13v12b0qcx-rosbash-1.14.6.drv
  /nix/store/jvzpclld7mvac59v5lw2x9ljwf5rbkjw-rosmake-1.14.6.drv
  /nix/store/8lzcrkrglyyd2w5q0vwjafcs55zbapjl-source.drv
  /nix/store/xpwly7q39i7xbnxcdczddvq7sdi9yp81-roscreate-1.14.6.drv
  /nix/store/vwjkp57pxx5pxm27hz9m59kh3i19hw8h-ros-1.14.6.drv
  /nix/store/lyqhq437m9zr7vwm36wcn5c5cd6k11nl-ros_comm-1.14.4.drv
  /nix/store/jg8bmqd98411gcjw6k336r97y8zx8z6q-substrate_ros_msgs-master.drv
  /nix/store/8hn4ncxn5ql2bpvnbr4hsd3kq66aaflz-robonomics_msgs-master.drv
these paths will be fetched (6.82 MiB download, 24.01 MiB unpacked):
  /nix/store/1nii7hnrw3cg8ci9r6pjxn1jd0c77jaf-python3.7-pycryptodomex-3.9.4
building '/nix/store/cfr1hj8krq5fmg0hhsbgahrg38zp2pi4-catkin-0.7.15.drv'...
unpacking sources
unpacking source archive /nix/store/p0s8hkndan2w0p9as70i3hqfr57bs3ab-source
source root is source
patching sources
configuring
fixing cmake files...
cmake flags: -DCMAKE_FIND_USE_SYSTEM_PACKAGE_REGISTRY=OFF -DCMAKE_FIND_USE_PACKAGE_REGISTRY=OFF -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_SKIP_BUILD_RPATH=ON -DBUILD_TESTING=OFF -DCMAKE_INSTALL_LOCALEDIR=/nix/store/j5j8sf9mvffpnlhnzpv05h7i4c4fsb4z-catkin-0.7.15/share/locale -DCMAKE_INSTALL_LIBEXECDIR=/nix/store/j5j8sf9mvffpnlhnzpv05h7i4c4fsb4z-catkin-0.7.15/libexec -DCMAKE_INSTALL_LIBDIR=/nix/store/j5j8sf9mvffpnlhnzpv05h7i4c4fsb4z-catkin-0.7.15/lib -DCMAKE_INSTALL_DOCDIR=/nix/store/j5j8sf9mvffpnlhnzpv05h7i4c4fsb4z-catkin-0.7.15/share/doc/ -DCMAKE_INSTALL_INFODIR=/nix/store/j5j8sf9mvffpnlhnzpv05h7i4c4fsb4z-catkin-0.7.15/share/info -DCMAKE_INSTALL_MANDIR=/nix/store/j5j8sf9mvffpnlhnzpv05h7i4c4fsb4z-catkin-0.7.15/share/man -DCMAKE_INSTALL_OLDINCLUDEDIR=/nix/store/j5j8sf9mvffpnlhnzpv05h7i4c4fsb4z-catkin-0.7.15/include -DCMAKE_INSTALL_INCLUDEDIR=/nix/store/j5j8sf9mvffpnlhnzpv05h7i4c4fsb4z-catkin-0.7.15/include -DCMAKE_INSTALL_SBINDIR=/nix/store/j5j8sf9mvffpnlhnzpv05h7i4c4fsb4z-catkin-0.7.15/sbin -DCMAKE_INSTALL_BINDIR=/nix/store/j5j8sf9mvffpnlhnzpv05h7i4c4fsb4z-catkin-0.7.15/bin -DCMAKE_INSTALL_NAME_DIR=/nix/store/j5j8sf9mvffpnlhnzpv05h7i4c4fsb4z-catkin-0.7.15/lib -DCMAKE_POLICY_DEFAULT_CMP0025=NEW -DCMAKE_OSX_SYSROOT= -DCMAKE_OSX_ARCHITECTURES=x86_64 -DCMAKE_FIND_FRAMEWORK=last -DCMAKE_STRIP=/nix/store/ffi3j388c39qbbskfqg1zw0x2lmbzhnk-binutils-2.31.1/bin/strip -DCMAKE_RANLIB=/nix/store/ffi3j388c39qbbskfqg1zw0x2lmbzhnk-binutils-2.31.1/bin/ranlib -DCMAKE_AR=/nix/store/ffi3j388c39qbbskfqg1zw0x2lmbzhnk-binutils-2.31.1/bin/ar -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DCMAKE_INSTALL_PREFIX=/nix/store/j5j8sf9mvffpnlhnzpv05h7i4c4fsb4z-catkin-0.7.15 -DCATKIN_ENABLE_TESTING=OFF -DSETUPTOOLS_DEB_LAYOUT=OFF
-- The C compiler identification is GNU 9.2.0
-- The CXX compiler identification is GNU 9.2.0
-- Check for working C compiler: /nix/store/1kn7fi3hhi33jms3113riyzwyn2yqpqd-gcc-wrapper-9.2.0/bin/gcc
-- Check for working C compiler: /nix/store/1kn7fi3hhi33jms3113riyzwyn2yqpqd-gcc-wrapper-9.2.0/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /nix/store/1kn7fi3hhi33jms3113riyzwyn2yqpqd-gcc-wrapper-9.2.0/bin/g++
-- Check for working CXX compiler: /nix/store/1kn7fi3hhi33jms3113riyzwyn2yqpqd-gcc-wrapper-9.2.0/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using CATKIN_DEVEL_PREFIX: /build/source/build/devel
-- Using CMAKE_PREFIX_PATH: /nix/store/9l2zg4lazdld9v3mhcmcmdh0cx0qf753-patchelf-0.9;/nix/store/1kn7fi3hhi33jms3113riyzwyn2yqpqd-gcc-wrapper-9.2.0;/nix/store/662pxfcxbldq4k00ck53bn33g04ysywk-binutils-wrapper-2.31.1;/nix/store/kzrvnyppsbb86vga4ww832fdck7yfk8n-python3.7-catkin_pkg-0.4.9;/nix/store/zbjznzbm1ldmhdnzxws1cm97pdcvqina-python3.7-pyparsing-2.4.6;/nix/store/ja04f3cmapzb3f2mvjrb883bfqclsirq-python3-3.7.6;/nix/store/jsx5s3fdd2zxs357sgbwsx932f1kwi4g-python3.7-docutils-0.16;/nix/store/ddivg8kiahl1kllshyz4shhyky8ppz2v-python3.7-python-dateutil-2.8.1;/nix/store/l9yvb1hg4prpzv91bkfw1mdpqax3l5m9-python3.7-six-1.14.0;/nix/store/16irg1bsnkyzp4rbmfa5df1b3kw55v4s-python3.7-setuptools_scm-3.4.3;/nix/store/8ydppw7ymyh32iqdjagcpzi9hh7vyd9w-python3.7-rospkg-1.1.7;/nix/store/fnyf2aki0gbf0zqk98b6nks89awcd5j5-python3.7-PyYAML-5.2;/nix/store/hh5z7zyfgsv38azgk43ync9yc6z4cv1r-empy-3.3.2;/nix/store/41irrnq4ki4yijrh1z2by148xhhws0cq-cmake-3.16.4
-- Found PythonInterp: /nix/store/ja04f3cmapzb3f2mvjrb883bfqclsirq-python3-3.7.6/bin/python (found version "3.7.6")
-- Using PYTHON_EXECUTABLE: /nix/store/ja04f3cmapzb3f2mvjrb883bfqclsirq-python3-3.7.6/bin/python
-- Using default Python package layout
-- Found PY_em: /nix/store/hh5z7zyfgsv38azgk43ync9yc6z4cv1r-empy-3.3.2/lib/python3.7/site-packages/em.py
-- Using empy: /nix/store/hh5z7zyfgsv38azgk43ync9yc6z4cv1r-empy-3.3.2/lib/python3.7/site-packages/em.py
-- Using CATKIN_ENABLE_TESTING: OFF
-- catkin 0.7.15
-- BUILD_SHARED_LIBS is on
Traceback (most recent call last):
  File "/build/source/build/catkin_generated/generate_cached_setup.py", line 22, in <module>
    code = generate_environment_script('/build/source/build/devel/env.sh')
  File "/build/source/cmake/../python/catkin/environment_cache.py", line 61, in generate_environment_script
    output = subprocess.check_output([env_script, sys.executable, '-c', python_code])
  File "/nix/store/ja04f3cmapzb3f2mvjrb883bfqclsirq-python3-3.7.6/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/nix/store/ja04f3cmapzb3f2mvjrb883bfqclsirq-python3-3.7.6/lib/python3.7/subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/nix/store/ja04f3cmapzb3f2mvjrb883bfqclsirq-python3-3.7.6/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/nix/store/ja04f3cmapzb3f2mvjrb883bfqclsirq-python3-3.7.6/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/build/source/build/devel/env.sh': '/build/source/build/devel/env.sh'
CMake Error at cmake/safe_execute_process.cmake:11 (message):

  execute_process(/nix/store/ja04f3cmapzb3f2mvjrb883bfqclsirq-python3-3.7.6/bin/python
  "/build/source/build/catkin_generated/generate_cached_setup.py") returned
  error code 1
Call Stack (most recent call first):
  cmake/all.cmake:207 (safe_execute_process)
  CMakeLists.txt:8 (include)


-- Configuring incomplete, errors occurred!
See also "/build/source/build/CMakeFiles/CMakeOutput.log".
builder for '/nix/store/cfr1hj8krq5fmg0hhsbgahrg38zp2pi4-catkin-0.7.15.drv' failed with exit code 1
cannot build derivation '/nix/store/8hn4ncxn5ql2bpvnbr4hsd3kq66aaflz-robonomics_msgs-master.drv': 1 dependencies couldn't be built
error: build of '/nix/store/8hn4ncxn5ql2bpvnbr4hsd3kq66aaflz-robonomics_msgs-master.drv', '/nix/store/jg8bmqd98411gcjw6k336r97y8zx8z6q-substrate_ros_msgs-master.drv' failed
```

</details>

**Comment by akru** [comment]
As you can see in your attached log warning:
“ warning: ignoring the user-specified setting 'sandbox', because it is a restricted setting and you are not a trusted user”

You should be trusted user to disable sandbox: https://www.mankier.com/5/nix.conf

**Comment by khssnv** [comment]
Yes, I just added my user to Nix trusted users to let it launch a build without sandboxing. There is a line in my `configuration.nix` added:
```nix
nix.trustedUsers = ["myusername"];
```
and it works. Thank you!
